openapi: 3.0.0

info:
    title: "US Presidents REST API"
    description: "An API about US Presidents"
    version: "1.0.0"

servers:
    - url: "/api"

components:
    schemas:
        President:
            type: "object"
            required:
                - number
                - lname
            properties:
                number:
                    type: "number"
                fname:
                    type: "string"
                lname:
                    type: "string"
                term_start: 
                    type: "integer"
                term_end:
                    type: "integer"
    parameters: 
        number:
            name: "number"
            description: "President number to get"
            in: path
            required: True
            schema:
                type: "integer"
        full_name:
            name: "full_name"
            description: "President to get by full name"
            in: path
            required: True
            schema:
                type: "string"
        note_id:
            name: "note_id"
            description: "ID of the note"
            in: path
            required: true
            schema:
                type: "integer"


paths:
    /presidents:
        get:
            operationId: "presidents.read_all"
            tags:
                - "Presidents"
            summary: "Read the list of US Presidents currently in database"
            responses:
                "200":
                    description: "Successfully read Presidents list"
        post:
            operationId: "presidents.create"
            tags:
                - President
            summary: "Create a President"
            requestBody:
                description: "President entry to create"
                required: True
                content: 
                    application/json:
                        schema:
                            x-body-name: "president"
                            $ref: "#/components/schemas/President"
            responses:
                "201":
                    description: "Successfully created a President entry."
    /presidents/{number}:
        get:
            operationId: "presidents.read_one"
            tags:
                - President
            summary: "Read one President entry"
            parameters:
                - $ref: "#/components/parameters/number"
            responses:
                "200":
                    description: "Successfully read President entry"
        put:
            tags:
                - President
            operationId: "presidents.update"
            summary: "Update a President entry"
            parameters: 
                - $ref: "#/components/parameters/number"
            responses:
                "200":
                    description: "Successfully updated person"
            requestBody:
                content:
                    application/json:
                        schema:
                            x-body-name: "president"
                            $ref: "#/components/schemas/President"
        delete:
            tags:
                - President
            operationId: "presidents.delete"
            summary: "Delete a President Entry"
            parameters:
                - $ref: "#/components/parameters/number"
            responses:
                "204":
                    description: "Successfully deleted President entry"
    /presidents/{full_name}:
        get:
            operationId: "presidents.read_one_by_full_name"
            tags:
                - President
            summary: "Read one President entry by full name"
            parameters:
                - $ref: "#/components/parameters/full_name"
            responses:
                "200":
                    description: "Successfully read President entry"
    /notes:
        post:
            operationId: "notes.create"
            tags:
                - Notes
            summary: "Create a note with associated President"
            parameters:
                - $ref: "#/components/parameters/number"
            requestBody:
                description: "Note to create"
                required: True
                content:
                    application/json:
                        schema:
                            x-body-name: "note"
                            type: "object"
                            properties:
                                president_id:
                                    type: "integer"
                                content:
                                    type: "string"
            responses:
                "201":
                    description: "Successfully created a note"
    /notes/{note_id}:
        get:
            operationId: "notes.read_one"
            tags:
                - Notes
            summary: "Read one note by ID"
            parameters:
                - $ref: "#/components/parameters/note_id"
            responses:
                "200":
                    description: "Successfully read one note"
        put:
            operationId: "notes.update"
            tags:
                - Notes
            summary: "Update note by ID"
            parameters:
                - $ref: "#/components/parameters/note_id"
            responses:
                "200":
                    description: "Successfully updated note"
            requestBody:
                content:
                    application/json:
                        schema:
                            x-body-name: "new_note"
                            type: "object"
                            properties:
                                content:
                                    type: "string"
        delete:
            operationId: "notes.delete"
            tags:
                - Notes
            summary: "Delete a note"
            parameters:
                - $ref: "#/components/parameters/note_id"
            responses:
                "204":
                    description: "Successfully deleted note"





